export const positive = [
  ["ts-class", "typescript", `export class Repository<T> {\n  private items: Map<string, T> = new Map();\n\n  add(id: string, item: T): void {\n    this.items.set(id, item);\n  }\n\n  get(id: string): T | undefined {\n    return this.items.get(id);\n  }\n}`],
  ["ts-interface", "typescript", `interface Config {\n  timeout: number;\n  retries: number;\n  onError?: (err: Error) => void;\n}\n\nfunction loadConfig(path: string): Config {\n  return JSON.parse(readFileSync(path, "utf8"));\n}`],
  ["js-arrow", "javascript", `const users = await fetch("/api/users").then(r => r.json());\nconst active = users.filter(u => u.active);\nconsole.log(\`Found \${active.length} active users\`);`],
  ["js-class-no-types", "javascript", `class Point {\n  constructor(x, y) {\n    this.x = x;\n    this.y = y;\n  }\n  distanceTo(other) {\n    return Math.sqrt((this.x - other.x) ** 2 + (this.y - other.y) ** 2);\n  }\n}\n\nconst p = new Point(0, 0);\nconsole.log(p.distanceTo(new Point(3, 4)));`],
  ["py-class", "python", `class Stack:\n    def __init__(self):\n        self.items = []\n\n    def push(self, item):\n        self.items.append(item)\n\n    def pop(self):\n        return self.items.pop()`],
  ["py-script", "python", `import json\nimport sys\n\ndef main():\n    data = json.load(sys.stdin)\n    for key, value in data.items():\n        print(f"{key}: {value}")\n\nif __name__ == "__main__":\n    main()`],
  ["bash-loop", "bash", `#!/usr/bin/env bash\nset -euo pipefail\n\nfor dir in */; do\n  echo "Building $dir"\n  (cd "$dir" && npm run build)\ndone`],
  ["bash-commands", "bash", `git checkout -b feature/new-thing\ngit add -A\ngit commit -m "add feature"\ngit push origin feature/new-thing`],
  ["json-config", "json", `{\n  "compilerOptions": {\n    "target": "es2022",\n    "strict": true,\n    "outDir": "./dist"\n  },\n  "include": ["src/**/*.ts"]\n}`],
  ["yaml-workflow", "yaml", `name: CI\non:\n  pull_request:\n    branches: [main]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm test`],
  ["sql-join", "sql", `SELECT o.id, o.total, c.name\nFROM orders o\nJOIN customers c ON c.id = o.customer_id\nWHERE o.status = 'paid'\nORDER BY o.created_at DESC;`],
  ["go-http", "go", `package main\n\nimport (\n\t"fmt"\n\t"net/http"\n)\n\nfunc handler(w http.ResponseWriter, r *http.Request) {\n\tfmt.Fprintln(w, "hello")\n}\n\nfunc main() {\n\thttp.HandleFunc("/", handler)\n\thttp.ListenAndServe(":8080", nil)\n}`],
  ["rust-struct", "rust", `struct Point { x: f64, y: f64 }\n\nimpl Point {\n    fn distance(&self, other: &Point) -> f64 {\n        ((self.x - other.x).powi(2) + (self.y - other.y).powi(2)).sqrt()\n    }\n}\n\nfn main() {\n    let p = Point { x: 0.0, y: 0.0 };\n    println!("{}", p.distance(&Point { x: 3.0, y: 4.0 }));\n}`],
  ["java-main", "java", `import java.util.List;\n\npublic class Main {\n    public static void main(String[] args) {\n        List<String> names = List.of("a", "b", "c");\n        for (String n : names) {\n            System.out.println(n);\n        }\n    }\n}`],
  ["csharp-console", "csharp", `using System;\nusing System.Collections.Generic;\n\nnamespace App {\n  class Program {\n    static void Main() {\n      var list = new List<int> { 1, 2, 3 };\n      Console.WriteLine(list.Count);\n    }\n  }\n}`],
  ["cpp-vector", "cpp", `#include <iostream>\n#include <vector>\n\nint main() {\n    std::vector<int> v = {1, 2, 3};\n    for (int x : v) {\n        std::cout << x << std::endl;\n    }\n    return 0;\n}`],
  ["html-page", "html", `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="utf-8">\n  <title>Demo</title>\n</head>\n<body>\n  <h1>Hello</h1>\n</body>\n</html>`],
  ["css-rules", "css", `.card {\n  display: flex;\n  flex-direction: column;\n  padding: 16px;\n  border-radius: 8px;\n}\n\n.card__title {\n  font-weight: 600;\n  color: #333;\n}`],
  ["dockerfile-node", "dockerfile", `FROM node:20-slim\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --omit=dev\nCOPY . .\nEXPOSE 3000\nCMD ["node", "server.js"]`],
  ["bash-shebang-only", "bash", `#!/bin/sh\necho "starting service"\nexec myservice --config /etc/myservice.conf`],
  ["python-shebang", "python", `#!/usr/bin/env python3\nimport argparse\n\nparser = argparse.ArgumentParser()\nparser.add_argument("--name")\nargs = parser.parse_args()\nprint(f"Hello {args.name}")`],
];

export const negative = [
  ["ascii-tree", `Host\n  1. Trigger: /dev-cycle ADA-123 "additional prompt"\n  2. jira show ADA-123 -> summary/description/AC\n  3. Build task prompt from ticket + user prompt\n  4. podman run --rm \\\n       -e ANTHROPIC_API_KEY=... \\\n       -e GIT_TOKEN=<scoped token>\n       dev-cycle-image`],
  ["prose-paragraph", `This extension improves how fenced code blocks are displayed to the user. It does not change any behavior of the underlying model, only how the terminal renders the final text after the model has finished responding to the user's request.`],
  ["dir-tree", `src/\n  index.ts\n  utils/\n    helper.ts\n    format.ts\n  components/\n    App.tsx`],
  ["markdown-table", `| Name | Age | City |\n|------|-----|------|\n| Bob  | 30  | NYC  |\n| Sue  | 25  | LA   |`],
  ["diff-snippet", `- const x = 1;\n+ const x = 2;\n  const y = 3;`],
  ["log-output", `2024-01-01 12:00:00 INFO Starting server on port 3000\n2024-01-01 12:00:01 INFO Connected to database\n2024-01-01 12:00:02 WARN Slow query detected (450ms)`],
  ["stack-trace-ish", `Error: something went wrong\n  at doThing (index.js:12)\n  at main (index.js:20)\n  at Object.<anonymous> (index.js:25)`],
  ["short-too-short", `ok`],
  ["numbered-list", `1. First step, open the terminal\n2. Second step, run the installer\n3. Third step, restart your machine`],
  ["key-value-notes", `Status: In Progress\nOwner: Alice\nDue: Friday`],
  ["freeform-shell-mention", `You should run npm install and then start the dev server before continuing with the rest of this guide.`],
  ["json-with-comments-invalid", `{\n  // this is a comment, not valid JSON\n  "name": "test"\n}`],
  ["html-fragment-no-doctype", `<div class="wrapper">\n  <span>hi</span>\n</div>`],
];
